# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tilda.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tilda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('tilda_content', tilda.fields.TildaPageField(on_delete=django.db.models.deletion.CASCADE, to='tilda.TildaPage', verbose_name='Tilda Page')),
            ],
        ),
    ]
